### ISSUE TITLE
I want these question solution in c++ and Java with proper explanation of code with time complexity. 

### ISSUE THREAD

**Issue by Kishan015** [Kishan015/Leecode_coding_Ques#1]
I want these question solution in c++ and Java with proper explanation of code with time complexity. 

https://leetcode.com/problems/two-sum/
 https://leetcode.com/problems/insert-delete-getrandom-o1/
 https://leetcode.com/problems/rotate-image/
 https://leetcode.com/problems/add-two-numbers/
 https://leetcode.com/problems/longest-palindromic-substring/
 https://leetcode.com/problems/string-to-integer-atoi/
 https://leetcode.com/problems/max-area-of-island/
 https://leetcode.com/problems/subarray-sums-divisible-by-k/
 https://leetcode.com/problems/merge-k-sorted-lists/
https://leetcode.com/problems/reverse-nodes-in-k-group/
https://leetcode.com/problems/copy-list-with-random-pointer/
https://leetcode.com/problems/word-break/
https://leetcode.com/problems/unique-paths/
https://leetcode.com/problems/range-sum-query-2d-immutable/
https://leetcode.com/problems/coin-change/
https://leetcode.com/problems/maximum-product-subarray/
https://leetcode.com/problems/implement-strstr/
https://leetcode.com/problems/merge-intervals/
https://leetcode.com/problems/trapping-rain-water/
https://leetcode.com/problems/edit-distance/
https://leetcode.com/problems/super-egg-drop/
https://leetcode.com/problems/longest-substring-without-repeating-characters/
https://leetcode.com/problems/basic-calculator-ii/
https://leetcode.com/problems/find-peak-element/
https://leetcode.com/problems/text-justification/
https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/
https://leetcode.com/problems/excel-sheet-column-title/
https://leetcode.com/problems/missing-number/
https://leetcode.com/problems/encode-and-decode-tinyurl/
https://leetcode.com/problems/valid-square/
https://leetcode.com/problems/number-of-digit-one/
https://leetcode.com/problems/remove-k-digits/
https://leetcode.com/problems/non-overlapping-intervals/
https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/
https://leetcode.com/problems/clone-graph/
https://leetcode.com/problems/house-robber-iii/
https://leetcode.com/problems/contain-virus/
https://leetcode.com/problems/binary-tree-inorder-traversal/   (USING STACK TOO)
https://leetcode.com/problems/redundant-connection/
https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/
https://leetcode.com/problems/verifying-an-alien-dictionary/
https://leetcode.com/problems/top-k-frequent-elements/
https://leetcode.com/problems/search-a-2d-matrix/
https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/
https://leetcode.com/problems/sort-colors/
https://leetcode.com/problems/subsets/
https://leetcode.com/problems/satisfiability-of-equality-equations/
https://leetcode.com/problems/sliding-window-median/
https://leetcode.com/explore/learn/card/trie/
https://leetcode.com/problems/ugly-number-ii/

**Comment by jay13makhija** [comment]
!assign

**Comment by jay13makhija** [comment]
Please assign it to me

**Comment by ShivanshDengla** [comment]
I can start working on the first problem if you want

**Comment by soham2312** [comment]
Please assign it to me
